# Generated by Django 3.2.12 on 2024-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Place', models.TextField()),
            ],
        ),
    ]
